name: Renovate
on:
  schedule:
    # Runs every day at 3:00 AM (UTC)
    - cron: '0 3 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: 'debug'
